### ISSUE TITLE
[EPIC] Create skeleton springboot app

### ISSUE THREAD

**Issue by LukeCole96** [LukeCole96/distributed-systems#1]
### Problem Statement
The objective of this project is to set up a foundational microservice application that includes basic operational features. The microservice will need to demonstrate the ability to monitor application health, retrieve application configuration, and provide JVM metrics. It should also include proper logging and error handling mechanisms. The service should be built with scalability in mind, following best practices for software architecture and development.

### Proposal
- Set up git repo
- Create skeleton API for private/status to return ok response to show app is up
- Create skeleton API for private/info to return application config properties in response to show app info
- Create skeleton API for private/metrics to return application (JVM) metrics
- Set up logback.xml and enable info mode for logging
- Implement a /healthcheck API to return downstream status
- Implement a global exception handler

### Stories
- [x] https://github.com/LukeCole96/distributed-systems/issues/2
- [x] https://github.com/LukeCole96/distributed-systems/issues/3
- [x] https://github.com/LukeCole96/distributed-systems/issues/4
- [ ] https://github.com/LukeCole96/distributed-systems/issues/6
- [ ] https://github.com/LukeCole96/distributed-systems/issues/5
