### ISSUE TITLE
Set up prometheus instance and scrape app private/metrics API (3)

### ISSUE THREAD

**Issue by LukeCole96** [LukeCole96/distributed-systems#14]
### Task
The application requires advanced monitoring and visualization capabilities to track metrics and performance in real-time. Integrating Prometheus for metric collection and Grafana for visualization will enhance the ability to monitor application health, performance, and usage, providing actionable insights for optimization.

### Pre-req
- Private/metrics API exposed and JVM metrics established via actuator

### Acceptance Criteria
- [] Set up docker container of prometheus 
- [] configure port 9000
- [] Set up prometheus config and define scrape intervals
- [] configure calling localhost/private/metrics API to scrape metrics

### Demo
show prometheus scraping jvm metrics for springboot app
